### ISSUE TITLE
Container won't start

### ISSUE THREAD

**Issue by mariwing** [adorobis/speedtest-CLI2mqtt#1]
There seems to be an issue with paths?

Traceback (most recent call last):
  File "/usr/src/app/./speedtest.py", line 308, in <module>
    run_speedtest()
  File "/usr/src/app/./speedtest.py", line 67, in run_speedtest
    process = subprocess.Popen([SPEEDTEST_PATH,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/app/speedtest'

**Comment by adorobis** [comment]
Try changing the path to speedtest in the config.ini file. I have it:
`SPEEDTEST_PATH=speedtest`

**Comment by adorobis** [comment]
Btw, in the meantime I've been working on making this container much lighter, you can find the alpine based image here:
adorobis/speedtest2mqtt:alpine
It should work with the provided config.ini defaults.

**Comment by mariwing** [comment]
Awesome, thank you for sharing your work on this :)

**Comment by adorobis** [comment]
I've updated the :latest image on docker hub as well, it is now based on the python:alpine image and is over 2x smaller.
