### ISSUE TITLE
Error: [0] Cannot read from socket (0 bytes read)

### ISSUE THREAD

**Issue by BertrumUK** [adorobis/speedtest-CLI2mqtt#7]
A friend of mine started having issues with this recently after it had been working fine. Looking at the logs we get the following error -

`published message on on topic speedtestdev/error at Mon Sep 18 10:01:24 2023
published message {
    "message": "Error: [0] Cannot read from socket (0 bytes read)",
    "level": "error",
    "timestamp": "2023-09-18T10:01:02Z"
} on topic speedtestdev/status_attributes at Mon Sep 18 10:01:24 2023
Log level: error
Message: Error: [0] Cannot read from socket (0 bytes read)
Timestamp: 2023-09-18T10:01:02Z`

I have tried re-deploying and starting over from scratch and there is no change. I tried disabling Adguard, but there was no change. 

It will run 1 test then throw the error and not run again unless the container is restarted.

![image](https://github.com/adorobis/speedtest-CLI2mqtt/assets/22644029/60378954-db44-4f0e-a4ea-5f7f3f8b8cb5)

any idea how to fix this ?

**Comment by adorobis** [comment]
Is the server configured? Sometimes some servers become unavailable and this might be the case here. Please share your config file so I could see if I face the same problem.
Please also share you docker config for this container.

**Comment by BertrumUK** [comment]
Hello,

Here is the config file, with the MQTT settings crossed out -

```
[DEFAULT]
SPEEDTEST_SERVERID=
SPEEDTEST_PATH=/usr/src/app/speedtest
REFRESH_INTERVAL=1800
DEBUG = 1
CONSOLE = 1
[MQTT]
# MQTT broker - IP
MQTTServer=192.168.1.154
# MQTT broker - Port
MQTTPort=1883
 # MQTT broker - keepalive
MQTTKeepalive=45
# MQTT broker - user - default: empty (disabled/no authentication)
MQTTUser=xxxxxxx
# MQTT broker - password - default: empty (disabled/no authentication)
MQTTPassword=xxxxxxx
[HA]
# Home Assistant send auto discovery for sensors
HAEnableAutoDiscovery=True
# Unique device ID (change this to be unique if running multiple instances)
HAAutoDiscoveryDeviceId=speedtestdev
# Device name shown in the frontend
HAAutoDiscoveryDeviceName=Speedtest.net-dev
# Device manufacturer shown in device info
HAAutoDiscoveryDeviceManufacturer=Speedtest.net
# Device model shown in device info
HAAutoDiscoveryDeviceModel=Speedtest.net CLI
```

We were forcing the server ID, but when it failed I reset it back.

**Comment by adorobis** [comment]
Please share your container config as well. I'm not able to reproduce so far, I'm using the following config for docker compose:
```
  speedtest:
    container_name: speedtest
    restart: unless-stopped
    image: adorobis/speedtest2mqtt:latest
    volumes:
      - /home/docker-data/speedtest/config:/usr/src/config
 ```

**Comment by adorobis** [comment]
btw, maybe change the parameter:
`CONSOLE=0`
Please also share full log from the container, maybe there would be some more hints.

**Comment by BertrumUK** [comment]
It was deployed using Portainer, so the compose file should match what you have configured. I tried using Stacks in Portainer, but it throws an error about root access - `failed to deploy a stack: validating /data/compose/5/docker-compose.yml: (root) Additional property speedtest is not allowed`

Here is the full error log -

`    "timestamp": "2023-09-18T10:31:24Z"
} on topic speedtestdev/status_attributes at Mon Sep 18 10:31:45 2023
Log level: error
Message: Error: [0] Cannot read from socket (0 bytes read)
Timestamp: 2023-09-18T10:31:24Z
Running Speedtest
Stdout: {"type":"result","timestamp":"2023-09-18T11:02:13Z","ping":{"jitter":0.318,"latency":5.508,"low":5.225,"high":5.881},"download":{"bandwidth":88582577,"bytes":1051380736,"elapsed":11912,"latency":{"iqm":8.034,"low":4.086,"high":35.633,"jitter":1.748}},"upload":{"bandwidth":45384548,"bytes":681669701,"elapsed":14996,"latency":{"iqm":7.347,"low":4.440,"high":16.666,"jitter":1.183}},"packetLoss":0,"isp":"Giganet Limited","interface":{"internalIp":"172.30.232.3","name":"eth0","macAddr":"02:42:AC:1E:E8:03","isVpn":false,"externalIp":"188.74.86.188"},"server":{"id":57318,"host":"speedtest.zzoomm.com","port":8080,"name":"Zzoomm Plc","location":"Slough","country":"United Kingdom","ip":"91.193.9.14"},"result":{"id":"642c3f95-1827-42e5-8ebf-fea99d2a46ca","url":"https://www.speedtest.net/result/c/642c3f95-1827-42e5-8ebf-fea99d2a46ca","persisted":true}}
Stderr: {"type":"log","timestamp":"2023-09-18T11:01:45Z","message":"Error: [0] Cannot read from socket (0 bytes read)","level":"error"}
Stderr: {"type":"log","timestamp":"2023-09-18T11:01:45Z","message":"Error: [0] Cannot read from socket (0 bytes read)","level":"error"}
published message on on topic speedtestdev/error at Mon Sep 18 11:02:13 2023
published message {
    "message": "Error: [0] Cannot read from socket (0 bytes read)",
    "level": "error",
    "timestamp": "2023-09-18T11:01:45Z"
} on topic speedtestdev/status_attributes at Mon Sep 18 11:02:13 2023
Log level: error
Message: Error: [0] Cannot read from socket (0 bytes read)
Timestamp: 2023-09-18T11:01:45Z
Successfully connected to MQTT broker
Running Speedtest
published message online on topic speedtestdev/status at Mon Sep 18 11:29:39 2023
Home Assistant MQTT Autodiscovery Topic Set: homeassistant/sensor/speedtest_net_[nametemp]/config
Sending autodiscover for homeassistant/sensor/speedtestdev_net_download/config
published message {"name": "Download", "has_entity_name": true, "availability_topic": "speedtestdev/status", "payload_available": "online", "payload_not_available": "offline", "unique_id": "speedtestdev-speedtestdev_net_download", "device": {"identifiers": ["speedtestdev"], "name": "Speedtest.net-dev", "manufacturer": "Speedtest.net", "model": "Speedtest.net CLI"}, "state_topic": "speedtestdev/download", "unit_of_measurement": "Mbit/s", "state_class": "measurement"} on topic homeassistant/sensor/speedtestdev_net_download/config at Mon Sep 18 11:29:40 2023
Sending autodiscover for homeassistant/sensor/speedtestdev_net_upload/config
published message {"name": "Upload", "has_entity_name": true, "availability_topic": "speedtestdev/status", "payload_available": "online", "payload_not_available": "offline", "unique_id": "speedtestdev-speedtestdev_net_upload", "device": {"identifiers": ["speedtestdev"], "name": "Speedtest.net-dev", "manufacturer": "Speedtest.net", "model": "Speedtest.net CLI"}, "state_topic": "speedtestdev/upload", "unit_of_measurement": "Mbit/s", "state_class": "measurement"} on topic homeassistant/sensor/speedtestdev_net_upload/config at Mon Sep 18 11:29:40 2023
Sending autodiscover for homeassistant/sensor/speedtestdev_net_ping/config
published message {"name": "Ping", "has_entity_name": true, "availability_topic": "speedtestdev/status", "payload_available": "online", "payload_not_available": "offline", "unique_id": "speedtestdev-speedtestdev_net_ping", "device": {"identifiers": ["speedtestdev"], "name": "Speedtest.net-dev", "manufacturer": "Speedtest.net", "model": "Speedtest.net CLI"}, "state_topic": "speedtestdev/ping", "unit_of_measurement": "ms", "json_attributes_topic": "speedtestdev/attributes", "state_class": "measurement"} on topic homeassistant/sensor/speedtestdev_net_ping/config at Mon Sep 18 11:29:40 2023
Sending autodiscover for homeassistant/sensor/speedtestdev_net_isp/config
published message {"name": "ISP", "has_entity_name": true, "availability_topic": "speedtestdev/status", "payload_available": "online", "payload_not_available": "offline", "unique_id": "speedtestdev-speedtestdev_net_isp", "device": {"identifiers": ["speedtestdev"], "name": "Speedtest.net-dev", "manufacturer": "Speedtest.net", "model": "Speedtest.net CLI"}, "state_topic": "speedtestdev/isp"} on topic homeassistant/sensor/speedtestdev_net_isp/config at Mon Sep 18 11:29:40 2023
Sending autodiscover for homeassistant/sensor/speedtestdev_net_server/config
published message {"name": "Server", "has_entity_name": true, "availability_topic": "speedtestdev/status", "payload_available": "online", "payload_not_available": "offline", "unique_id": "speedtestdev-speedtestdev_net_server", "device": {"identifiers": ["speedtestdev"], "name": "Speedtest.net-dev", "manufacturer": "Speedtest.net", "model": "Speedtest.net CLI"}, "state_topic": "speedtestdev/server"} on topic homeassistant/sensor/speedtestdev_net_server/config at Mon Sep 18 11:29:40 2023
Sending autodiscover for homeassistant/binary_sensor/speedtestdev_net_status/config
published message {"name": "Status", "has_entity_name": true, "availability_topic": "speedtestdev/status", "payload_available": "online", "payload_not_available": "offline", "unique_id": "speedtestdev-speedtestdev_net_status", "device": {"identifiers": ["speedtestdev"], "name": "Speedtest.net-dev", "manufacturer": "Speedtest.net", "model": "Speedtest.net CLI"}, "state_topic": "speedtestdev/error", "device_class": "problem", "entity_category": "diagnostic", "payload_on": "on", "payload_off": "off", "json_attributes_topic": "speedtestdev/status_attributes"} on topic homeassistant/binary_sensor/speedtestdev_net_status/config at Mon Sep 18 11:29:40 2023
Stdout: {"type":"result","timestamp":"2023-09-18T11:30:07Z","ping":{"jitter":0.480,"latency":5.631,"low":5.125,"high":6.119},"download":{"bandwidth":92727670,"bytes":1170034775,"elapsed":13214,"latency":{"iqm":8.052,"low":3.745,"high":23.372,"jitter":1.850}},"upload":{"bandwidth":31664073,"bytes":416603849,"elapsed":13021,"latency":{"iqm":7.308,"low":4.019,"high":22.086,"jitter":1.548}},"packetLoss":0,"isp":"Giganet Limited","interface":{"internalIp":"172.30.232.3","name":"eth0","macAddr":"02:42:AC:1E:E8:03","isVpn":false,"externalIp":"188.74.86.188"},"server":{"id":57318,"host":"speedtest.zzoomm.com","port":8080,"name":"Zzoomm Plc","location":"Slough","country":"United Kingdom","ip":"91.193.9.14"},"result":{"id":"52186b28-ae1e-406d-a8b8-2a4ffd80f9e5","url":"https://www.speedtest.net/result/c/52186b28-ae1e-406d-a8b8-2a4ffd80f9e5","persisted":true}}
Stderr: {"type":"log","timestamp":"2023-09-18T11:29:39Z","message":"Error: [0] Cannot read from socket (0 bytes read)","level":"error"}
Stderr: {"type":"log","timestamp":"2023-09-18T11:29:39Z","message":"Error: [0] Cannot read from socket (0 bytes read)","level":"error"}
published message on on topic speedtestdev/error at Mon Sep 18 11:30:07 2023
published message {
    "message": "Error: [0] Cannot read from socket (0 bytes read)",
    "level": "error",
    "timestamp": "2023-09-18T11:29:39Z"
} on topic speedtestdev/status_attributes at Mon Sep 18 11:30:07 2023
Log level: error
Message: Error: [0] Cannot read from socket (0 bytes read)
Timestamp: 2023-09-18T11:29:39Z
Running Speedtest
Stdout: {"type":"result","timestamp":"2023-09-18T12:00:29Z","ping":{"jitter":0.463,"latency":5.964,"low":5.573,"high":6.539},"download":{"bandwidth":95371421,"bytes":1234370528,"elapsed":15004,"latency":{"iqm":6.052,"low":3.668,"high":17.947,"jitter":1.336}},"upload":{"bandwidth":41339391,"bytes":244722393,"elapsed":5812,"latency":{"iqm":7.719,"low":4.129,"high":11.240,"jitter":1.251}},"packetLoss":0,"isp":"Giganet Limited","interface":{"internalIp":"172.30.232.3","name":"eth0","macAddr":"02:42:AC:1E:E8:03","isVpn":false,"externalIp":"188.74.86.188"},"server":{"id":57318,"host":"speedtest.zzoomm.com","port":8080,"name":"Zzoomm Plc","location":"Slough","country":"United Kingdom","ip":"91.193.9.14"},"result":{"id":"7c1c2456-2c65-4feb-95b9-c258f1669b77","url":"https://www.speedtest.net/result/c/7c1c2456-2c65-4feb-95b9-c258f1669b77","persisted":true}}
Stderr: {"type":"log","timestamp":"2023-09-18T12:00:07Z","message":"Error: [0] Cannot read from socket (0 bytes read)","level":"error"}
Stderr: {"type":"log","timestamp":"2023-09-18T12:00:07Z","message":"Error: [0] Cannot read from socket (0 bytes read)","level":"error"}
published message on on topic speedtestdev/error at Mon Sep 18 12:00:29 2023
published message {
    "message": "Error: [0] Cannot read from socket (0 bytes read)",
    "level": "error",
    "timestamp": "2023-09-18T12:00:07Z"
} on topic speedtestdev/status_attributes at Mon Sep 18 12:00:29 2023
Log level: error
Message: Error: [0] Cannot read from socket (0 bytes read)
Timestamp: 2023-09-18T12:00:07Z
Running Speedtest
Stdout: {"type":"result","timestamp":"2023-09-18T12:30:47Z","ping":{"jitter":0.294,"latency":5.196,"low":4.848,"high":5.606},"download":{"bandwidth":89592888,"bytes":482543296,"elapsed":5402,"latency":{"iqm":7.863,"low":5.056,"high":18.621,"jitter":1.616}},"upload":{"bandwidth":46582473,"bytes":517761557,"elapsed":11208,"latency":{"iqm":9.151,"low":4.198,"high":14.844,"jitter":1.533}},"packetLoss":0,"isp":"Giganet Limited","interface":{"internalIp":"172.30.232.3","name":"eth0","macAddr":"02:42:AC:1E:E8:03","isVpn":false,"externalIp":"188.74.86.188"},"server":{"id":57318,"host":"speedtest.zzoomm.com","port":8080,"name":"Zzoomm Plc","location":"Slough","country":"United Kingdom","ip":"91.193.9.14"},"result":{"id":"2670a872-87df-4653-ac4f-968e963e43eb","url":"https://www.speedtest.net/result/c/2670a872-87df-4653-ac4f-968e963e43eb","persisted":true}}
Stderr: {"type":"log","timestamp":"2023-09-18T12:30:30Z","message":"Error: [0] Cannot read from socket (0 bytes read)","level":"error"}
Stderr: {"type":"log","timestamp":"2023-09-18T12:30:30Z","message":"Error: [0] Cannot read from socket (0 bytes read)","level":"error"}
published message on on topic speedtestdev/error at Mon Sep 18 12:30:48 2023
published message {
    "message": "Error: [0] Cannot read from socket (0 bytes read)",
    "level": "error",
    "timestamp": "2023-09-18T12:30:30Z"
} on topic speedtestdev/status_attributes at Mon Sep 18 12:30:48 2023
Log level: error
Message: Error: [0] Cannot read from socket (0 bytes read)
Timestamp: 2023-09-18T12:30:30Z
Running Speedtest
Stdout: {"type":"result","timestamp":"2023-09-18T13:01:01Z","ping":{"jitter":0.503,"latency":4.517,"low":4.112,"high":5.557},"download":{"bandwidth":95306981,"bytes":415967424,"elapsed":4306,"latency":{"iqm":5.981,"low":3.427,"high":12.089,"jitter":1.266}},"upload":{"bandwidth":28426630,"bytes":226321562,"elapsed":7707,"latency":{"iqm":7.820,"low":4.603,"high":18.226,"jitter":1.749}},"packetLoss":0,"isp":"Giganet Limited","interface":{"internalIp":"172.30.232.3","name":"eth0","macAddr":"02:42:AC:1E:E8:03","isVpn":false,"externalIp":"188.74.86.188"},"server":{"id":57318,"host":"speedtest.zzoomm.com","port":8080,"name":"Zzoomm Plc","location":"Slough","country":"United Kingdom","ip":"91.193.9.14"},"result":{"id":"fcf861d0-a587-4260-82e1-2d86d1de99c5","url":"https://www.speedtest.net/result/c/fcf861d0-a587-4260-82e1-2d86d1de99c5","persisted":true}}
Stderr: {"type":"log","timestamp":"2023-09-18T13:00:48Z","message":"Error: [0] Cannot read from socket (0 bytes read)","level":"error"}
Stderr: {"type":"log","timestamp":"2023-09-18T13:00:48Z","message":"Error: [0] Cannot read from socket (0 bytes read)","level":"error"}
published message on on topic speedtestdev/error at Mon Sep 18 13:01:01 2023
published message {
    "message": "Error: [0] Cannot read from socket (0 bytes read)",
    "level": "error",
    "timestamp": "2023-09-18T13:00:48Z"
} on topic speedtestdev/status_attributes at Mon Sep 18 13:01:01 2023
Log level: error
Message: Error: [0] Cannot read from socket (0 bytes read)
Timestamp: 2023-09-18T13:00:48Z`

**Comment by adorobis** [comment]
Hmm. I don't have experience with portainer. Firstly I would change this parameter CONSOLE to 0: `CONSOLE=0` in the config.ini file. Not sure if it matters at all but it works for me :)

**Comment by adorobis** [comment]
Btw, above error is coming from the speedtest application. Not sure why it fails... I have not experienced it so far - only occasionally and usually it worked at second run 30 minutes later.

**Comment by BertrumUK** [comment]
I had already changed `CONSOLE=0` but there was no change, that and the log was only enabled once the test had stopped running. It seems that once this error occurs further tests do not run. The container is still running, but you get no new tests carried out. 

Maybe if Speedtest is throwing this error, the test should still run depending on the update schedule.

**Comment by adorobis** [comment]
The problem is that it actually runs again after defined period (default is 1800 seconds). You can also see it in the log you've provided: after the `Cannot read from socket` error it gets data successfully 30 minutes later. In the log you can see that it starts:
`2023-09-18T11:01:45Z Successfully connected to MQTT broker`
later:
`2023-09-18T11:29:39Z","message":"Error: [0] Cannot read from socket`
and 30 minutes later works ok again:
`2023-09-18T12:00:29Z","ping":{"jitter":0.463,"latency":5.964,"low":5.573,"high":6.539}`
and later you have two runs with the error:
`2023-09-18T12:30:30Z","message":"Error: [0] Cannot read from socket`
`2023-09-18T13:00:48Z","message":"Error: [0] Cannot read from socket`
This shows that the app is trying every 30 minutes and even the first attempt failed here.

Not sure what the problem really is, I can't replicate it. With the simple docker compose config it all works ok. I have the socket errors most likely during internet connection outages. Maybe your ISP does not like that you run those tests? Could you try with a server in a different country?

**Comment by BertrumUK** [comment]
ok, changing to other servers stops this error occurring. It is strange as the local server works fine from a browser.

Happy to close this. Thanks for your assistance.
